### ISSUE TITLE
Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by dfuentes87** [zyachel/quetre#101]
**Server:**
Debian 11, 64 bit; 1 CPU 2.65 Ghz; 2 GB RAM
**Quetre:** 
Docker build (latest) using Nginx frontend proxy

**Troubleshooting:** 
Confirmed not OOM-killer, have enough disk space, fully removed container and rebuilt the container

**Issue:**
95% of my requests regardless of question looked up end up in a 500 Internal Server Error with the following error in the logs:

```
2023-04-09T19:12:52.938566622Z  🔴 Unexpected token u in JSON at position 0
2023-04-09T19:12:52.938621384Z SyntaxError: Unexpected token u in JSON at position 0
2023-04-09T19:12:52.938626294Z     at JSON.parse (<anonymous>)
2023-04-09T19:12:52.938642161Z     at file:///app/fetchers/getAnswers.js:16:16
2023-04-09T19:12:52.938646118Z     at Array.map (<anonymous>)
2023-04-09T19:12:52.938649765Z     at getAnswers (file:///app/fetchers/getAnswers.js:15:34)
2023-04-09T19:12:52.938653819Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-04-09T19:12:52.938657546Z     at async getOrSetCache (file:///app/utils/getOrSetCache.js:9:23)
2023-04-09T19:12:52.938661156Z     at async file:///app/controllers/viewController.js:50:23
```

That is the full error at each load of a page. If I keep refreshing, eventually the page does correctly show the answer, but then continuing to refresh goes back to a 500 ISE with the same error in the logs. 

**Screenshot:**
<img width="1457" alt="Screenshot 2023-04-09 at 3 30 07 PM" src="https://user-images.githubusercontent.com/11722608/230792770-a77ec9dd-0c53-452a-b31e-f335b46a82c3.png">

**Comment by zyachel** [comment]
I'll take a look into this.
